name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    
    env:
      NODE_ENV: test
      LOG_LEVEL: debug

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - name: Run tests with logging
      run: |
        # Force output buffering off for Node.js
        NODE_OPTIONS=--no-force-async-hooks-checks npm test || {
          echo "Tests failed, but continuing to show logs"
          cat logs/*.log 2>/dev/null || echo "No log files found"
          exit 1
        }